name: Tests

on: pull_request

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          # - 7.3
          # - 7.2
          # - 5.6
        wp:
          - "*"
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306: 3306
    env:
      WP_DB_USER: wp
      WP_DB_PASS: password
      WP_DB_NAME: wp_tests
    name: PHP ${{ matrix.php }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Create database
        run: |
          mysql -u root -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
          mysql -u root -e "CREATE DATABASE ${WP_DB_NAME};"
      - run: composer validate --strict
      - run: composer require --dev --no-update roots/wordpress:${{ matrix.wp }} wp-phpunit/wp-phpunit:${{ matrix.wp }}
      - run: composer install
      - run: composer show
      - name: Run PHPUnit
        run: composer test
