name: Tests

on: pull_request

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 7.3
          - 7.2
          - 5.6
    services:
      mysql:
        image: mysql
    env:
      WP_DB_USER: wp
      WP_DB_PASS: password
      WP_DB_NAME: wp_tests
      WP_VERSION: "*"
    name: PHP ${{ matrix.php }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Create database
        run: |
          mysql -u root --host mysql -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
          mysql -u root --host mysql -e "CREATE DATABASE ${WP_DB_NAME};"
      - run: composer validate --strict
      - run: composer require --dev --no-update roots/wordpress:${WP_VERSION} wp-phpunit/wp-phpunit:${WP_VERSION}
      - run: composer install
      - run: composer show
      - name: Run PHPUnit
        run: composer test
